package com.cjss.student.entity;
import javax.persistence.*;
import java.time.LocalDate;

@Entity
@Table(name="student_fee_entity")
public class StudentFeeEntity {
	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)       // Id is autogenerated in sequence(1,2,3...).Other values passed as input will be ignored.
	private Integer studentRollNo;
	@Column
	private int feeAmount;
	@Column
	private LocalDate date;

	public Integer getStudentRollNo() {
		return studentRollNo;
	}

	public void setStudentRollNo(Integer studentRollNo) {
		this.studentRollNo = studentRollNo;
	}

	public int getFeeAmount() {
		return feeAmount;
	}

	public void setFeeAmount(int feeAmount) {
		this.feeAmount = feeAmount;
	}

	public LocalDate getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = LocalDate.parse(date);
	}
}
