package com.cjss.student.entity;
import javax.persistence.*;

@Entity
@Table(name="subject_entity")
public class SubjectEntity {
	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)       // Id is autogenerated in sequence(1,2,3...).Other values passed as input will be ignored.
	private Integer subjectNumber;
	@Column
	private String subjectName;

	public Integer getSubjectNumber() {
		return subjectNumber;
	}

	public void setSubjectNumber(Integer subjectNumber) {
		this.subjectNumber = subjectNumber;
	}

	public String getSubjectName() {
		return subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}
}
