package com.cjss.employee.entity;

import javax.persistence.*;

@Entity
@Table(name="department_details")
public class DepartmentEntity {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)       // Id is autogenerated in sequence(1,2,3...).Other values passed as input will be ignored.
    private int deptId;
    @Column
    private String deptName;
    @Column
    private String location;

    public int getDeptId() {
        return deptId;
    }

    public void setDeptId(int deptId) {
        this.deptId = deptId;
    }

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
}
