package com.cjss.employee.entity;
import javax.persistence.*;

@Entity
@Table(name="employee_entity")
public class EmployeeEntity {
	@Id
	@GeneratedValue(strategy= GenerationType.AUTO)       // Id is autogenerated in sequence(1,2,3...).Other values passed as input will be ignored.
	private Integer employeeId;
	@Column
	private String employeeName;
	@Column
	private int Salary;
	@Column
	private int locationId;
	@Column
	private int deptId;

	@Column
	private String benefits;
	public String getEmployeeName() {
		return employeeName;
	}
	public int getSalary() {
		return Salary;
	}
	public int getLocationId() {
		return locationId;
	}
	public int getDeptId() {
		return deptId;
	}
	public void setEmployeeId(Integer employeeId) {

		this.employeeId = employeeId;
	}
	public void setEmployeeName(String employeeName) {

		this.employeeName = employeeName;
	}
	public void setSalary(int Salary) {
		this.Salary = Salary;
	}
	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}
	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}
	public Integer getEmployeeId() {
		return employeeId;
	}

	public String getBenefits() {
		return benefits;
	}

	public void setBenefits(String benefits) {
		this.benefits = benefits;
	}
}
