package com.cjss.employee.entity;

import javax.persistence.*;

@Entity
@Table(name="location_details")
public class LocationEntity {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)       // Id is autogenerated in sequence(1,2,3...).Other values passed as input will be ignored.
    private Integer locationId;
    @Column
    private String locationName;
    @Column
    private String locationCountry;

    public Integer getLocationId() {
        return locationId;
    }

    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    public String getLocationName() {
        return locationName;
    }

    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    public String getLocationCountry() {
        return locationCountry;
    }

    public void setLocationCountry(String locationCountry) {
        this.locationCountry = locationCountry;
    }

}
