package com.cjss.DailyActivities.entity;

import javax.persistence.*;

@Entity
@Table(name="food_item")
public class FoodItem {
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)       // Id is autogenerated in sequence(1,2,3...).Other values passed as input will be ignored.
    private Integer date;
    @Column
    private Integer breakfastItem;  //Time spent on breakfast in mins
    @Column
    private Integer lunchItem;  //Time spent on breakfast in mins
    @Column
    private Integer dinnerItem; //Time spent on breakfast in mins
    @OneToOne(mappedBy = "foodItem")
    private FoodTime foodTime;

    public Integer getDate() {
        return date;
    }

    public void setDate(Integer date) {
        this.date = date;
    }

    public Integer getBreakfastItem() {
        return breakfastItem;
    }

    public void setBreakfastItem(Integer breakfastTime) {
        this.breakfastItem = breakfastTime;
    }

    public Integer getLunchItem() {
        return lunchItem;
    }

    public void setLunchItem(Integer lunchTime) {
        this.lunchItem = lunchTime;
    }

    public Integer getDinnerItem() {
        return dinnerItem;
    }

    public void setDinnerItem(Integer dinnerTime) {
        this.dinnerItem = dinnerTime;
    }
}
